set nocompatible              " be iMproved, required
filetype off                  " required

"" Vundle stuff
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'itchyny/lightline.vim'
call vundle#end()

syntax on
filetype plugin indent on 
colorscheme jellybeans

"" Vim configs
set encoding=utf-8
set nocompatible               " Use Vim defaults
set hidden                     " Quick buffer switching
set ruler                      " Show cursor position 
set laststatus=2               " Show statusline even when no window split 
set number                     " Line numbers
set cursorline
set scrolloff=2                " Keep 2 scroll lines above/below cursor
set fillchars=vert:\           " Remove ugly | in seperators 
set noerrorbells               " Disable annoying beeps
set visualbell                 "Visual bell instead of beeping
set expandtab                  " Tab -> Space
set tabstop=4                  " Tabs count for 4 columns
set softtabstop=4              " Tab == 4 spaces
set shiftwidth=4               " 4 Columns with reindent options
set autoindent                 " Ignore case
set smartindent                " Except with capitals 
set nohlsearch
set incsearch                  " Increment search
set ignorecase                 " Case-insensitive search;
set smartcase                  " Search becomes case sensitive if caps used
set nobackup
set noswapfile
set history=50                 " Keep 50 lines of command line history
set shortmess+=I               " No startup message
set nolazyredraw
set mouse=a 
set clipboard=unnamed

"" Override vim defaults
hi CursorLineNr    term=bold cterm=bold ctermfg=Yellow gui=bold

""Statusline configs
set noshowmode

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ }

